import streamlit as st
import pandas as pd
from datetime import datetime

from src.ai.llm_agent import analyze_data, generate_fix_code

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="CommerceDoctor AI",
    layout="wide",
)

# ---------------- SIDEBAR ----------------
st.sidebar.title("🧭 Navigation")
st.sidebar.markdown("""
- Upload Data  
- AI Analysis  
- Fix & Repair  
- Monitoring  
""")

st.sidebar.info("AI + Data Engineering Platform")

# ---------------- HEADER ----------------
st.title("🧠 CommerceDoctor AI")
st.markdown("### Agentic Data Quality & Auto-Repair Platform")

# ---------------- SESSION STATE ----------------
if "logs" not in st.session_state:
    st.session_state.logs = []

def log(message):
    st.session_state.logs.append(f"{datetime.now().strftime('%H:%M:%S')} - {message}")

# ---------------- FILE UPLOAD ----------------
file = st.file_uploader("📂 Upload Orders JSON")

if file:
    df = pd.read_json(file)
    log("File uploaded")

    # ---------------- DATA PREVIEW ----------------
    st.subheader("📊 Data Preview")
    st.dataframe(df, use_container_width=True)

    # ---------------- METRICS ----------------
    st.subheader("📈 Quick Stats")
    col1, col2, col3 = st.columns(3)

    col1.metric("Total Rows", len(df))
    col2.metric("Null Customers", df["customer_id"].isna().sum())
    col3.metric("Negative Amounts", (df["amount"] < 0).sum())

    # ---------------- 🔥 DETECTION (IMPORTANT) ----------------
    duplicates = df[df.duplicated("order_id")]
    nulls = df[df["customer_id"].isna()]
    negatives = df[df["amount"] < 0]

    summary = {
        "duplicate_count": len(duplicates),
        "null_count": len(nulls),
        "negative_count": len(negatives)
    }

    # ---------------- AI SECTION ----------------
    st.markdown("---")
    st.subheader("🧠 AI Analysis & Code Generation")

    colA, colB = st.columns(2)

    with colA:
        if st.button("🔍 Run AI Analysis"):
            with st.spinner("Analyzing data..."):
                result = analyze_data(summary)   # ✅ FIXED
            log("AI analysis completed")
            st.success("Analysis Completed")
            st.write(result)

    with colB:
        if st.button("💻 Generate Fix Code"):
            with st.spinner("Generating PySpark code..."):
                code = generate_fix_code(summary)   # ✅ FIXED
            log("Code generated by AI")
            st.success("Code Generated")
            st.code(code, language="python")

    # ---------------- AGENT EXECUTION ----------------
    st.markdown("---")
    st.subheader("🤖 AI Agent Execution")

    if st.button("⚡ Auto Fix Data"):

        with st.spinner("Applying fixes..."):

            issues = analyze_data(summary)   # ✅ FIXED
            code = generate_fix_code(summary)   # ✅ FIXED

            # Deterministic fix (REAL LOGIC)
            fixed_df = df.copy()
            fixed_df = fixed_df[fixed_df["amount"] >= 0]
            fixed_df = fixed_df[fixed_df["customer_id"].notna()]
            fixed_df = fixed_df.drop_duplicates("order_id")

        log("Auto fix applied")

        st.success("Data Fixed Successfully")

        tab1, tab2, tab3 = st.tabs(["🧠 AI Insights", "💻 Generated Code", "✅ Fixed Data"])

        with tab1:
            st.write(issues)

        with tab2:
            st.code(code)

        with tab3:
            st.dataframe(fixed_df, use_container_width=True)

        # ---------------- KPIs ----------------
        st.subheader("📊 KPIs After Fix")
        k1, k2 = st.columns(2)
        k1.metric("Total Revenue", fixed_df["amount"].sum())
        k2.metric("Total Orders", len(fixed_df))

        # ---------------- CHART ----------------
        st.subheader("📉 Revenue Distribution")
        chart_df = fixed_df.groupby("customer_id")["amount"].sum()
        st.bar_chart(chart_df)

    # ---------------- LOGS ----------------
    st.markdown("---")
    st.subheader("📜 Pipeline Logs")

    for log_item in st.session_state.logs[::-1]:
        st.text(log_item)